#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Apply wallpaper on qtile startup

WALLPAPER="$HOME/.config/qtile/wallpapers/wallpaper.png"
hsetroot -root -cover "$WALLPAPER"
