#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/qtile"
RASI="$DIR/theme/rofi/runner.rasi"

# Run
rofi \
    -show run \
	-theme ${RASI}
